version: 0.2

env:
  variables:
    WORKING_DIR: lambda

phases:

  install:
    commands:
      - echo "Installing Composer dependencies and Node.js packages..."
      - cd $WORKING_DIR && composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev & npm install -g serverless@3 --cache /root/.npm && wait
      - echo "Checking AWS credentials..."
  pre_build:
    commands:
      - export BRANCH_NAME=$(echo ${CODEBUILD_WEBHOOK_HEAD_REF:-refs/heads/dev} | awk -F'/' '{print $NF}')
      - echo "Branch name is $BRANCH_NAME"
      # Map branch to proper stage
      - |
        if [ "$BRANCH_NAME" = "main" ]; then
          export DEPLOY_STAGE="main"
          echo "✅ Main branch detected → Deploying to PRODUCTION (main)"
        elif [ "$BRANCH_NAME" = "stage" ]; then
          export DEPLOY_STAGE="stage"
          echo "✅ Stage branch detected → Deploying to STAGING (stage)"
        elif [ "$BRANCH_NAME" = "dev" ]; then
          export DEPLOY_STAGE="dev"
          echo "✅ Dev branch detected → Deploying to DEVELOPMENT (dev)"
        else
          echo "❌ Unknown branch: $BRANCH_NAME - Skipping deployment"
          exit 0
        fi
  build:
    commands:
      - echo "Deploying to environment: $DEPLOY_STAGE"
      - cd $WORKING_DIR && serverless deploy --stage $DEPLOY_STAGE
      - echo "Deployment completed successfully."

artifacts:
  files:
    - '**/*'  # Include all files generated during the build

cache:
  paths:
    - '/root/.cache/composer/**/*'  # Cache Composer files
    - '/root/.npm/**/*'  # Cache npm packages
    - './node_modules/**/*'  # Cache Node.js dependencies
    - './vendor/**/*'  # Cache PHP dependencies
