version: 0.2

env:
  variables:
    WORKING_DIR: lambda

phases:

  install:
    commands:
      - echo "Installing Composer dependencies and Node.js packages..."
      - cd $WORKING_DIR && composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev & npm install -g serverless@3 --cache /root/.npm && wait
      - echo "Checking AWS credentials..."
  pre_build:
    commands:
      - export BRANCH_NAME=$(echo ${CODEBUILD_WEBHOOK_HEAD_REF:-refs/heads/dev} | awk -F'/' '{print $NF}')
      - echo "Branch name is $BRANCH_NAME"
  build:
    commands:
      - echo "Packaging and deploying with Serverless from $WORKING_DIR directory..."
      - echo "Current directory before deployment:" && pwd
      - echo "Listing files in current directory:" && ls -la
      - echo "Changing to lambda directory..." && cd lambda
      - echo "Current directory after cd:" && pwd
      - echo "Listing files in lambda directory:" && ls -la serverless.yml
      - serverless deploy --stage $BRANCH_NAME
      - echo "Deployment completed successfully - ListStackResources permission added."

artifacts:
  files:
    - '**/*'  # Include all files generated during the build

cache:
  paths:
    - '/root/.cache/composer/**/*'  # Cache Composer files
    - '/root/.npm/**/*'  # Cache npm packages
    - './node_modules/**/*'  # Cache Node.js dependencies
    - './vendor/**/*'  # Cache PHP dependencies
